In [2]:
import numpy as np
# 1. Create a 3x3 matrix containing numbers 1 through 9
practice_matrix = np.arange(1, 10).reshape(3, 3)

# 2. Add 100 to every element using vectorized broadcasting
result = practice_matrix + 100

print("Practice Matrix:\n", result)
print("Shape:", result.shape)
print("Data Type:", result.dtype)

Practice Matrix:
 [[101 102 103]
 [104 105 106]
 [107 108 109]]
Shape: (3, 3)
Data Type: int64
